### ISSUE TITLE
Updated to react 16 and getting Error

### ISSUE THREAD

**Issue by forWorkAtML** [davidtheclark/focus-trap-react#17]
I just went into my package.json and updated to react 16 and focus trap is giving me this error:

`Error: You can't have a focus-trap without at least one focusable element`

```
"focus-trap-react": "^3.0.4",
"react": "^16.0.0",
"react-dom": "^16.0.0",
```

Not really sure what happened exactly. Looking into it but wanted to let you know.

**Comment by davidtheclark** [comment]
Are you sure you changed nothing except the React version?

**Comment by forWorkAtML** [comment]
yes
As soon as I changed back no error
```
"react": "^15.6.1",
"react-dom": "^15.6.1",
```

**Comment by forWorkAtML** [comment]
closing this out.

Not really exactly sure why previously it was not throwing the error but I edited my HTML with tabIndex and it appears that the problem has gone away.
