### ISSUE TITLE
autoFocus and initialFocus

### ISSUE THREAD

**Issue by matthewoates** [davidtheclark/focus-trap-react#3]
You get `autoFocus` for free. My understanding is that whenever a focusable element with `autoFocus` is added by react, it automatically gets focused.

`autoFocus` doesn't work right now with focus-trap-react.
- If `initialFocus` is unspecified, it ignores any `autoFocus` elements and focuses the first element.
- If you pass a selector that matches no elements, `focus-trap-react` throws an error and breaks the component.
- If you pass a valid selector, then you're not taking advantage of the convenience and simplicity of `autoFocus` in the first place

**Comment by davidtheclark** [comment]
Makes sense. I'd say that "the convenience and simplicity of `autoFocus`" is really not significantly greater than typing a valid selector for the component you want to focus — but if that's how you like to do it, I understand. Open to a PR making this `autoFocus`-compatible.

**Comment by davidtheclark** [comment]
@matthewoates With the latest update to focus-trap, `autoFocus` does in fact work. I added a demo showing this and a note to the README explaining the one caveat I've seen.

**Comment by a-eid** [comment]
autoFocus does not work with FocusTrap.
