### ISSUE TITLE
Demo page appears to be broken

### ISSUE THREAD

**Issue by mturley** [davidtheclark/focus-trap-react#36]
Looking at the demo page at http://davidtheclark.github.io/focus-trap-react/demo/, I notice a few issues:

* In the "first focus, no escape" demo, the "activate trap" button does nothing. The button disappears, and nothing appears.
* the "special element" and "demo autofocus" demos do not appear to render at all.

Notably, when I build and run the demo page locally, everything works fine.

**Comment by davidtheclark** [comment]
Just needed an update. Should be fixed now. Thanks @mturley!
