### ISSUE TITLE
clickOutsideDeactivates option does not work on iOS devices

### ISSUE THREAD

**Issue by mturley** [davidtheclark/focus-trap-react#37]
The `clickOutsideDeactivates` option appears to work fine in the regular [focus-trap demo page](http://davidtheclark.github.io/focus-trap/demo/) (not focus-trap-react), on all browsers and devices I've tested.

However, when using [the `focus-trap-react` demo page](http://davidtheclark.github.io/focus-trap-react/demo/) on my iPad, when I tap the "activate trap" button on the "special element" demo, tapping outside the trap does not deactivate it.

This problem seems to be unique to the react version of the library, and unique to iOS. Testing on Android and on desktop browsers, it works fine. And the normal library's demo of `clickOutsideDeactivates` seems to work fine on iOS.

**Comment by davidtheclark** [comment]
@mturley now that I've updated the demo site, this seems to work fine. Are you still seeing unexpected behavior?

**Comment by mturley** [comment]
@davidtheclark, thanks for the quick response! Yes, when I test the "special element" section of the demo page on my iPad, after I activate the trap, I can't seem to deactivate the trap by tapping anywhere but on the deactivate button. The word "with" just retains focus no matter what I do. On my desktop browser and on my Android phone, I can click/tap outside to deactivate it. It seems to be an iOS-specific issue. I can reproduce it in Chrome and Safari on an iPad.

For context, we're seeing the same behavior with our Dropdown menu here, which uses a FocusTrap: http://patternfly-react.surge.sh/patternfly-4/components/dropdown. Once opening the dropdown, I can't close it by tapping outside it on iOS devices.

**Comment by davidtheclark** [comment]
@mturley I'm using an iPhone, so we're both testing iOS ... The fact that focus remains on the word "with" doesn't mean the focus trap isn't deactivated — it just means that wherever you clicked hasn't *taken* the focus. Try clicking on one of the buttons that activate another focus trap. If another focus trap can be activated, that means your original focus trap is no longer active.

**Comment by mturley** [comment]
Hmm, that's fair. It's just strange to me that the behavior is inconsistent on iOS vs Android. I'll take a closer look to see if it's actually not being deactivated.

Thanks for your help so far, and thanks for the great library!

**Comment by mturley** [comment]
@davidtheclark, you were right, the focus trap is getting deactivated, but focus is not being changed. So the issue I'm seeing isn't in your library after all. Sorry for the red herring, and thanks for the help!
