### ISSUE TITLE
Bump focus-trap-react to use focus-trap 4.0.2

### ISSUE THREAD

**Issue by colmbrady** [davidtheclark/focus-trap-react#38]
Id like to bump focus-trap-react to use 4.0.2 of focus-trap. We tested bumping to 4.0.2 in the current version of focus-trap-react to test if it fixes a nested focus trap issue we were having and it looks good.

Ill prepare a P.R for your review.

**Comment by setek** [comment]
Was your error with nesting a ...

`TypeError: Cannot read property 'ownerDocument' of null`

in tabbable.js by any chance?

**Comment by colmbrady** [comment]
@setek yes, pretty sure that was the issue we were having. So that led us to look into a fix and noticed the work done already in the downstream library. My environment is not ale to verify that 100% though

**Comment by colmbrady** [comment]
I updated the package lock by hand and it seems to be working for me on installs. I did not want to regenerate it from scratch as the diff is quite large. At the moment there is only a diff for the two dependency bumps.

@davidtheclark do you want to accept this P.R? Or do you have alternative plans for how to bump this library?

**Comment by davidtheclark** [comment]
Version bump is released in 6.0.0.

Thanks @colmbrady!
