### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by ithinco** [davidtheclark/focus-trap-react#4]
```
<FocusTrap active={"0" === this.state.active }>
  <button>Hello</button>
</FocusTrap>

<FocusTrap active={"1" === this.state.active }>
   <button>Hello2</button>
</FocusTrap>
```

I’m using the active flag to change focus between two FocusTraps.

active == "0" works fine
active == "1" works fine, the first FocusTrap loses focus
active == "0" again, works fine, the first FocusTrap gains focus
active == "1" the focus disappears!

I looked at the source code of focus-trap and can't figure it out.

Thanks.

**Comment by davidtheclark** [comment]
@ithinco Sorry this has slipped through my radar. The best way to show & debug this would be to create a new demo that exemplifies the problem.

**Comment by davidtheclark** [comment]
This has been sitting for a long time, so I am going to close. Please re-open if the problem still exists and can be demonstrated.
