### ISSUE TITLE
Add className to focus-trap div

### ISSUE THREAD

**Issue by boaz0** [davidtheclark/focus-trap-react#40]
Hi,

We are using `focus-trap-react` in our [Modal](https://1372-pr-patternfly-react-patternfly.surge.sh/patternfly-4/components/modal) component.

I noticed that `focus-trap-react` is wrapping the `childern` inside a div. Unfortunately, this `div` is causing a conflict in our `css` and it would be helpful if we could pass a specific `class` that will align the modal correctly.

Is there a way to pass that as a prop? Or to solve this conflict?

Thanks.

**Comment by boaz0** [comment]
N/M. Looking at the source code, I found out that you can pass `className`, `id` and etc to FocusTrap which will add it to the `div` element.

Although, it is very confusing that `README.md` doesn't mention anything about that.
Maybe I missed it or something.

**Comment by davidtheclark** [comment]
Looks like it's missing from the docs. PR welcome. Thanks @boaz0.

**Comment by boaz0** [comment]
Sure. I will take care of it!
