### ISSUE TITLE
Change focus after focus-trap unmounts requires setTimeout

### ISSUE THREAD

**Issue by jameschetwood** [davidtheclark/focus-trap-react#42]
Im using focus-trap in a modal component. When the modal is closed I need to set the focus on a specific element (using a ref). I have this working in a setTimeout but it doesn't work without. Is this expected or is this a code smell? 

Here is my code. The modal is closed and focus is set based on a URL change provided by React Router. 

```
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.buttonRef = React.createRef();
  }

  componentDidUpdate(prevProps) {
    if (this.props.url === '' && prevProps.url = "old-url") {
      console.log('target element: ', this.buttonRef.current.firstChild)

      // This doenst work if not in a setTimeout
      // this.buttonRef.current.firstChild.focus();
      setTimeout(() => {
        this.buttonRef.current.firstChild.focus();
      }, 1);
    }
  }
```

**Comment by davidtheclark** [comment]
What if you set the focus-trap option `returnFocusOnDeactivate: false`? See https://github.com/davidtheclark/focus-trap#focustrap--createfocustrapelement-createoptions

**Comment by jameschetwood** [comment]
`returnFocusOnDeactivate` is already set to `false`. `returnFocusOnDeactivate` works great except sometimes the button that triggered the modal no longer exists by the time the modal is closed, in which case I need to focus on a different button.

Also modals are controlled by the url hash so they're kinda 'global' rather than being within a component in the normal React way. This is why there's some weirdness in `componentDidUpdate`. To be honest this has turned out to be really problematic and will need refactoring so no worries if there's no easy solution. Turns out breaking React's component modal was a bad call, who knew? ;-)
