### ISSUE TITLE
focus-trap version bump

### ISSUE THREAD

**Issue by jmrog** [davidtheclark/focus-trap-react#5]
Hope not to be a nuisance, but can we get a new release of this that includes the latest version of focus-trap (2.0.2)?

**Comment by davidtheclark** [comment]
@jmrog If you just reinstall your npm dependencies you should get that latest version, since it's just a patch release.

**Comment by jmrog** [comment]
Ah, you're right, there's a caret (`^`) in the package.json. My mistake. Thanks!
