### ISSUE TITLE
Can focus trap version be bumped to.5.0.2 on this repo to use allowOutsideClick feature

### ISSUE THREAD

**Issue by soumyajitz** [davidtheclark/focus-trap-react#52]
Is it possible to release a newer version of this repo with latest version from original focustrap repo so that newer features can be used?

**Comment by vinodh99** [comment]
We are waiting for this feature to be merged please

**Comment by brotzky** [comment]
To anyone that really needs this feature now it's not too hard to copy and paste this file:
https://github.com/davidtheclark/focus-trap-react/blob/master/src/focus-trap-react.js

and install the latest version of https://github.com/davidtheclark/focus-trap in your project.

You can then expose whichever APIs you want in your FocusTrap component :).
Even update it to Hooks and add some Types if you're feeling wild.

**Comment by cullylarson** [comment]
Would love to be able to use the fix from [davidtheclark/focus-trap#81](https://github.com/davidtheclark/focus-trap/issues/81) in `focus-trap-react` as well.

**Comment by stefcameron** [comment]
We haven't published an updated package yet, so not closing this issue yet in spite of taking #71.

**Comment by stefcameron** [comment]
Closing this now that 7.0.0 has been published with 591fa9a3ffa0748509db20a4f6d1cd6a7a2d10b6 and focus-trap dependency is now updated to `^5.1.0`. 🎉
