### ISSUE TITLE
Please fetch focus-trap v5.0.2

### ISSUE THREAD

**Issue by 9melons** [davidtheclark/focus-trap-react#70]
Hi, we have to use allowOutsideClick function provided by v5.0.2 of focus-trap
Possible to upgrade it please?

**Comment by jon64digital** [comment]
I have just run into this exact problem. I am using allowOutsideClick in my react app and I'm trying to upgrade it to Typescript right now. I have run into the following error...

**Type '{ allowOutsideClick: boolean; onDeactivate: () => void; }' is not assignable to type 'Options'**

I have tracked this down to the fact that the typings in focus-trap don't include this attribute in 4.0.2 which is the version which the most up to date focus-trap-react has in it's package.json

**Comment by stefcameron** [comment]
I'm closing this as a duplicate of #52. The request is the same. I hope to publish an updated package soon that will have the updated downstream dependency.
